import { Movie } from "../models/Movie";

export const rawList: any[] = [
  {
    id: 1,
    title: "War of the Worlds ",
    year: 1953,
    genres: ["science-fiction", "action"],
    summary:
      "The residents of a small town are excited when a flaming meteor lands in the hills, until they discover it is the first of many transport devices from Mars bringing an army of invaders invincible to any man-made weapon, even the atomic bomb.",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/fq/i8/ee/vv/war%20of%20the%20worlds-1200-1200-675-675-crop-000000.jpg?k=59ab741a51",
    cast: [
      "Gene Barry",
      "Ann Robinson",
      "Lewis Martin",
      "Les Tremayne",
      "Some Popular Actor",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/4/7/4/6/2/47462-the-war-of-the-worlds-0-230-0-345-crop.jpg?k=4314fe4050",
    userRating: 3.4,
    runtime: 85,
    tagline:
      "Mighty panorama of Earth-shaking fury as an army from Mars invades!",
    directors: ["Byron Haskin"],
    myRating: 7.5,
    label: "Criterion",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200830212207505_cover.jpg?w=800&h=600&crop=1",
    watchedDate: "August 30, 2020",
    content: [
      "Here we go, week 1: Sci-Fi.  I wanted to start with a sub-genre that is less “pure” horror and more tangential.  Since the War of the Worlds Criterion release recently came out, this was a good excuse to watch it.  Overall, it’s a pretty good movie given its age.  Looks good, for sure.  The ending was a little abrupt.  I know you’re reading this, Future Me, but just <em>in case</em> someone else is reading it, I won’t spoil it.  I liked that the movie gets going right away, no 30 minutes of setup or anything.  It was interesting seeing the panic and confusion in the early scenes.  Also, my ears perked up at hearing the doctor’s name, Clayton Forrester (hmm..)  Ok, that’s one movie down, ~45 to go..",
      "7.5/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 1",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
  },
  {
    id: 2,
    title: "It Came From Beneath the Sea ",
    year: 1955,
    genres: ["adventure", "science-fiction", "horror"],
    summary:
      "A giant octopus, whose feeding habits have been affected by radiation from H-Bomb tests, rises from the Mindanao Deep to terrorize the California Coast.",
    backdrop: null,
    cast: [
      "Kenneth Tobey",
      "Faith Domergue",
      "Donald Curtis",
      "Some Popular Actress",
      "Chuck Griffiths",
      "Some Popular Actor",
      "Ian Keith",
      "Dean Maddox Jr.",
      "Harry Lauter",
      "Richard W. Peterson",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/3/2/3/9/1/32391-it-came-from-beneath-the-sea-0-230-0-345-crop.jpg?k=e0c35c50b2",
    userRating: 2.82,
    runtime: 79,
    tagline: "IT CRUSHES! KILLS! DESTROYS!",
    directors: ["Robert Gordon"],
    myRating: 5.5,
    label: "Other",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200831100900833_cover-2.jpg?w=800&h=600&crop=1",
    watchedDate: "August 31, 2020",
    content: [
      "This was a bit of a step back compared to <strong>War of the Worlds</strong>.  More dated, the weird semi-love triangle was not my bag and the movie was pretty slow to get started.  A lot of uninteresting characters doing uninteresting things, except for the part where they showed the squid NOT eating the fish.  I wonder why that squid (the actor, not the character) didn’t eat those fish?  Good acting, I guess.  The Ray Harryhausen effects are the only thing notable, and they were fun in a cheesy way, but not a super interesting monster, just a giant squid.  The other movie in this blu-ray 2-pack, <strong>20 Million Miles to Earth (1957)</strong> had a more memorable creature, whatever that thing was.",
      "5.5/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 2",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
  },
  {
    id: 3,
    title: "Galaxy of Terror ",
    year: 1981,
    genres: ["adventure", "horror", "action", "science-fiction"],
    summary:
      "As a lone spaceship proceeds on its long voyage across space, the crew are surprised to encounter a strange pyramid form. Surprise turns to horror as one by one, they discover that their darkest nightmares are all starting to become real. The pyramid has to be behind it all somehow, but how can they save themselves from its influence?",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/b9/dg/wj/x4/galaxy%20of%20terror-1200-1200-675-675-crop-000000.jpg?k=0f2f581766",
    cast: [
      "Edward Albert",
      "Erin Moran",
      "Ray Walston",
      "Bernard Behrens",
      "Zalman King",
      "Robert Englund",
      "Taaffe O'Connell",
      "Sid Haig",
      "Grace Zabriskie",
      "Jack Blessing",
      "Mary Ellen O'Neill",
      "Some Popular Actress",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/3/3/2/8/9/33289-galaxy-of-terror-0-230-0-345-crop.jpg?k=cfd7d2f042",
    userRating: 2.61,
    runtime: 81,
    tagline: "ALIEN was the beginning… Hell Has Just Been Relocated!",
    directors: ["Bruce D. Clark"],
    myRating: 6,
    label: "Scream Factory (Other)",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200831122019959_cover.jpg?w=800&h=600&crop=1",
    watchedDate: "August 31, 2020",
    content: [
      "Two in one day, I’m cruising along now.  Here’s an idea: Freddy Krueger, Joanie (without Chachi), the teacher from Fast Times at Ridgemont High, Susan’s mom from Seinfeld and Captain Spaulding in space fighting aliens.  You son of a bitch, I’m in.  Of course it’s pretty clearly an Alien rip-off, but it seems like some effort was made.  The environments are pretty cool, even if a little low budget.  It wasn’t great, but it scratches that early 80s sci-fi itch.",
      "6/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 3",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
  },
  {
    id: 4,
    title: "Forbidden World ",
    year: 1982,
    genres: ["science-fiction", "horror"],
    summary:
      "In the distant future, a federation marshal arrives at a research lab on a remote planet where a genetic experiment has gotten loose and begins feeding on the dwindling scientific group.",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/cw/zc/n1/up/forbidden-world-1200-1200-675-675-crop-000000.jpg?k=058d931a8b",
    cast: [
      "Jesse Vint",
      "Dawn Dunlap",
      "June Chadwick",
      "Linden Chiles",
      "Fox Harris",
      "Ray Oliver",
      "Scott Paulin",
      "Some Popular Actress",
      "Michael Bowen",
      "Don Olivera",
      "Don Keith Opper",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/2/2/8/2/0/22820-forbidden-world-0-230-0-345-crop.jpg?k=8f258576a2",
    userRating: 2.79,
    runtime: 77,
    tagline: "Part alien … part human …  all nightmare.",
    directors: ["Allan Holzman"],
    label: "Scream Factory (Other)",
    img: "https://einysrentals.files.wordpress.com/2020/09/00100lrportrait_00100_burst20200901111848124_cover.jpg?w=800&h=600&crop=1",
    watchedDate: "September 1, 2020",
    content: [
      "I thought <strong>Galaxy of Terror</strong> was an Alien ripoff.. but THIS is an Alien ripoff.  If I didn’t have this journal, I guess years from now, I wouldn’t be able to remember which is which.  But luckily, I’ll lay out some differences for Future Me’s sake:",
      "<li>G: Mostly outside on the planet.  F: All inside the ship</li><li>G: Recognizable cast.  F: Unrecognizable except Jeanine from Spinal Tap</li><li>G: 90% Alien F: 95% Alien</li>",
      "The music was not bad and the <s>Xenomorph</s> creature was not bad, but yeah.. it’s a pretty cheap movie.  Maybe just slightly above <strong>Galaxy of Terror</strong>, but I just enjoy the cheap little spaceship interior more, I guess.",
      "6.5/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 4",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
  },
];

export const modeledList: Movie[] = [
  {
    id: "1",
    title: "War of the Worlds ",
    year: 1953,
    genres: ["science-fiction", "action"],
    summary:
      "The residents of a small town are excited when a flaming meteor lands in the hills, until they discover it is the first of many transport devices from Mars bringing an army of invaders invincible to any man-made weapon, even the atomic bomb.",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/fq/i8/ee/vv/war%20of%20the%20worlds-1200-1200-675-675-crop-000000.jpg?k=59ab741a51",
    cast: [
      "Gene Barry",
      "Ann Robinson",
      "Lewis Martin",
      "Les Tremayne",
      "Some Popular Actor",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/4/7/4/6/2/47462-the-war-of-the-worlds-0-230-0-345-crop.jpg?k=4314fe4050",
    userRating: 3.4,
    runtime: "85",
    tagline:
      "Mighty panorama of Earth-shaking fury as an army from Mars invades!",
    directors: ["Byron Haskin", "Another Director"],
    label: "Criterion",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200830212207505_cover.jpg?w=800&h=600&crop=1",
    content: [
      "Here we go, week 1: Sci-Fi.  I wanted to start with a sub-genre that is less “pure” horror and more tangential.  Since the War of the Worlds Criterion release recently came out, this was a good excuse to watch it.  Overall, it’s a pretty good movie given its age.  Looks good, for sure.  The ending was a little abrupt.  I know you’re reading this, Future Me, but just <em>in case</em> someone else is reading it, I won’t spoil it.  I liked that the movie gets going right away, no 30 minutes of setup or anything.  It was interesting seeing the panic and confusion in the early scenes.  Also, my ears perked up at hearing the doctor’s name, Clayton Forrester (hmm..)  Ok, that’s one movie down, ~45 to go..",
      "7.5/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 1",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
    date: "August 30, 2020",
    rating: "7.5",
    runtimeMins: 85,
    ratingDiff: "0.70",
  },
  {
    id: "2",
    title: "It Came From Beneath the Sea ",
    year: 1955,
    genres: ["adventure", "science-fiction", "horror"],
    summary:
      "A giant octopus, whose feeding habits have been affected by radiation from H-Bomb tests, rises from the Mindanao Deep to terrorize the California Coast.",
    backdrop: "",
    cast: [
      "Kenneth Tobey",
      "Faith Domergue",
      "Donald Curtis",
      "Some Popular Actress",
      "Chuck Griffiths",
      "Some Popular Actor",
      "Ian Keith",
      "Dean Maddox Jr.",
      "Harry Lauter",
      "Richard W. Peterson",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/3/2/3/9/1/32391-it-came-from-beneath-the-sea-0-230-0-345-crop.jpg?k=e0c35c50b2",
    userRating: 2.82,
    runtime: "79",
    tagline: "IT CRUSHES! KILLS! DESTROYS!",
    directors: ["Robert Gordon"],
    label: "Other",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200831100900833_cover-2.jpg?w=800&h=600&crop=1",
    content: [
      "This was a bit of a step back compared to <strong>War of the Worlds</strong>.  More dated, the weird semi-love triangle was not my bag and the movie was pretty slow to get started.  A lot of uninteresting characters doing uninteresting things, except for the part where they showed the squid NOT eating the fish.  I wonder why that squid (the actor, not the character) didn’t eat those fish?  Good acting, I guess.  The Ray Harryhausen effects are the only thing notable, and they were fun in a cheesy way, but not a super interesting monster, just a giant squid.  The other movie in this blu-ray 2-pack, <strong>20 Million Miles to Earth (1957)</strong> had a more memorable creature, whatever that thing was.",
      "5.5/10",
    ],
    categoryCls: "halloween_2020A",
    subCategory: "Week 1",
    order: "Movie 2",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020A",
    date: "August 31, 2020",
    rating: "5.5",
    runtimeMins: 79,
    ratingDiff: "-0.14",
  },
  {
    id: "3",
    title: "Galaxy of Terror ",
    year: 1981,
    genres: ["adventure", "horror", "action", "science-fiction"],
    summary:
      "As a lone spaceship proceeds on its long voyage across space, the crew are surprised to encounter a strange pyramid form. Surprise turns to horror as one by one, they discover that their darkest nightmares are all starting to become real. The pyramid has to be behind it all somehow, but how can they save themselves from its influence?",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/b9/dg/wj/x4/galaxy%20of%20terror-1200-1200-675-675-crop-000000.jpg?k=0f2f581766",
    cast: [
      "Edward Albert",
      "Erin Moran",
      "Ray Walston",
      "Bernard Behrens",
      "Zalman King",
      "Robert Englund",
      "Taaffe O'Connell",
      "Sid Haig",
      "Grace Zabriskie",
      "Jack Blessing",
      "Mary Ellen O'Neill",
      "Some Popular Actress",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/3/3/2/8/9/33289-galaxy-of-terror-0-230-0-345-crop.jpg?k=cfd7d2f042",
    userRating: 2.61,
    runtime: "81",
    tagline: "ALIEN was the beginning… Hell Has Just Been Relocated!",
    directors: ["Bruce D. Clark"],
    label: "Scream Factory (Other)",
    img: "https://einysrentals.files.wordpress.com/2020/08/00100lrportrait_00100_burst20200831122019959_cover.jpg?w=800&h=600&crop=1",
    content: [
      "Two in one day, I’m cruising along now.  Here’s an idea: Freddy Krueger, Joanie (without Chachi), the teacher from Fast Times at Ridgemont High, Susan’s mom from Seinfeld and Captain Spaulding in space fighting aliens.  You son of a bitch, I’m in.  Of course it’s pretty clearly an Alien rip-off, but it seems like some effort was made.  The environments are pretty cool, even if a little low budget.  It wasn’t great, but it scratches that early 80s sci-fi itch.",
      "6/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 3",
    tags: ["Sci-Fi Horror B"],
    format: "Blu Ray",
    category: "Halloween 2020",
    date: "August 31, 2020",
    rating: "6",
    runtimeMins: 81,
    ratingDiff: "0.78",
  },
  {
    id: "4",
    title: "Forbidden World ",
    year: 1982,
    genres: ["science-fiction", "horror"],
    summary:
      "In the distant future, a federation marshal arrives at a research lab on a remote planet where a genetic experiment has gotten loose and begins feeding on the dwindling scientific group.",
    backdrop:
      "https://a.ltrbxd.com/resized/sm/upload/cw/zc/n1/up/forbidden-world-1200-1200-675-675-crop-000000.jpg?k=058d931a8b",
    cast: [
      "Jesse Vint",
      "Dawn Dunlap",
      "June Chadwick",
      "Linden Chiles",
      "Fox Harris",
      "Ray Oliver",
      "Scott Paulin",
      "Some Popular Actress",
      "Michael Bowen",
      "Don Olivera",
      "Don Keith Opper",
    ],
    poster:
      "https://a.ltrbxd.com/resized/film-poster/2/2/8/2/0/22820-forbidden-world-0-230-0-345-crop.jpg?k=8f258576a2",
    userRating: 2.79,
    runtime: "77",
    tagline: "Part alien … part human …  all nightmare.",
    directors: ["Allan Holzman", "Another Director"],
    label: "Scream Factory (Other)",
    img: "https://einysrentals.files.wordpress.com/2020/09/00100lrportrait_00100_burst20200901111848124_cover.jpg?w=800&h=600&crop=1",
    content: [
      "I thought <strong>Galaxy of Terror (1981)</strong> was an Alien ripoff.. but THIS is an Alien ripoff.  If I didn’t have this journal, I guess years from now, I wouldn’t be able to remember which is which.  But luckily, I’ll lay out some differences for Future Me’s sake:",
      "<li>G: Mostly outside on the planet.  F: All inside the ship</li><li>G: Recognizable cast.  F: Unrecognizable except Jeanine from Spinal Tap</li><li>G: 90% Alien F: 95% Alien</li>",
      "The music was not bad and the <s>Xenomorph</s> creature was not bad, but yeah.. it’s a pretty cheap movie.  Maybe just slightly above <strong>Galaxy of Terror</strong>, but I just enjoy the cheap little spaceship interior more, I guess.",
      "6.5/10",
    ],
    categoryCls: "halloween_2020",
    subCategory: "Week 1",
    order: "Movie 4",
    tags: ["Sci-Fi Horror"],
    format: "Blu Ray",
    category: "Halloween 2020",
    date: "September 1, 2020",
    rating: "6.5",
    runtimeMins: 77,
    ratingDiff: "0.92",
  },
];
